### ISSUE TITLE
채팅 엔터키 외 구현사항

### ISSUE THREAD

**Issue by choonghyunryu** [choonghyunryu/shinyGPT#1]
### Task

- 이광춘 박사님 피드백 외
    - [x] 채팅 시 엔터키 이벤트 반응 구현
    - [x] 예제 프롬프트 추가 
        - 그림 그리기, 텍스트 생성에 대한 예제 프롬프트        
        - ~~README 도움말에 추가할까?~~
        - ~~프롬프트 예시 웹 페이지 하나를 만들어 앱에 추가할까?~~   
        - Vigenttes에 추가
    - [ ] 채팅 시, 마지막 답변이 화면에 보이도록 자동 스크롤
    - [x] 메뉴부분(헤더) 상단에 고정
        - 현재는 채팅 창이 스크롤되면 헤더가 안보임
